[DOCUMENTATION TESTIMONIAL]OT246-93
alkemyTech/OT246-Node pull request #102
Opened 2022-08-16 00:29 UTC by MRobertaMendoza

Description

AS developer
I WANT to have a documentation of Testimonios endpoints
TO have references of its operation

Criteria of acceptance:
The different endpoints must be documented, specifying the data model, mandatory fields, request format and its example.
EVIDENCE
![testimonial_1](https://user-images.githubusercontent.com/64031295/184758384-28fb3d50-d725-4e36-88e1-65139cf859b7.jpg)
![testimonial](https://user-images.githubusercontent.com/64031295/184758406-77f39205-3357-441d-bc56-0a9afcd87572.jpg)

2022-08-16 00:35 UTC, gabodmc approved these changes

2022-08-16 00:35 UTC, gabodmc commented on docs/swagger.js
> +}
recordar mergear primero el pr de swagger  para no tener conflictos con esto

2022-08-16 00:52 UTC, ghnoob requested changes
```yaml
security:
  - bearerAuth: []
```
agregale eso a los endpoints que necesitan jwt para que se puedan probar desde la misma pagina de documentacion, como aca:
https://github.com/alkemyTech/OT246-Node/blob/3042c86fafeb6c05f5082c54a831654150e521bd/routes/auth.js#L179-L185

2022-08-16 08:02 UTC, MRobertaMendoza commented on docs/swagger.js
> +}
ok gracias.

2022-08-18 23:04 UTC, ghnoob approved these changes

2022-08-19 11:26 UTC, ignacioborraz approved these changes

2022-08-19 11:26 UTC, ignacioborraz commented on docs/testimonial.js
> + *          description: content for testimonial *
puede ser que haya un asterisco de más al final?

2022-08-19 11:26 UTC, ignacioborraz commented on docs/testimonial.js
> + *      200:
no seria 201?

2022-08-19 14:54 UTC, ghnoob commented on docs/testimonial.js
> + *      200:
creo que le hiciste review a un commit viejo

2022-08-19 17:12 UTC, merged