[Documentation] Members endpoints
alkemyTech/OT246-Node pull request #106
Opened 2022-08-16 20:14 UTC by bgalacho

Descripción

COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Miembros
PARA tener referencias de su funcionamiento

Criterios de aceptación:
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

2022-08-16 20:25 UTC, ghnoob requested changes
Agregale el security a cada endpoint para que se pueda poner el token desde la pagina
```yaml
      security:
        - bearerAuth: []
```

no veo documentadas las respuestas de los errores de autenticacion/autorizacion

2022-08-16 23:08 UTC, ghnoob commented on routes/members.js
> +router.delete('/:id', authUserAdmin, destroy)
guarda con esto, creo que se te paso

2022-08-17 13:26 UTC, bgalacho commented on routes/members.js
> +router.delete('/:id', authUserAdmin, destroy)
Dale Rodri ahi lo veo!

2022-08-17 18:29 UTC, kamp3r commented
Excelente! con evidencia!

2022-08-17 18:29 UTC, kamp3r approved these changes

2022-08-17 19:14 UTC, ghnoob approved these changes

2022-08-17 20:00 UTC, merged