[DOCUMENTATION] - Add Documentation to What's New OT246-91
alkemyTech/OT246-Node pull request #107
Opened 2022-08-16 21:58 UTC by Samuel0023

## Description
AS a developer
I WANT to have a documentation of the News endpoints
TO have references of its operation

Criteria of acceptance:
The different endpoints must be documented, specifying the data model, mandatory fields, request format and its example.

## Evidence 
![image](https://user-images.githubusercontent.com/38141029/184991704-0e45930d-6105-4cfd-a595-7f7d9515a023.png)

2022-08-16 22:51 UTC, ghnoob requested changes
Faltaria tambien documentar las respuestas de autenticacion/autorizacion y el PUT de `news/{id}`

2022-08-16 22:51 UTC, ghnoob commented on routes/news.js
> + *        required: true
me parece que no tendria que ser requerido y tendrias que agregarle `default: 0` de ultima

2022-08-16 22:51 UTC, ghnoob commented on routes/news.js
> + *         - $ref: '#/components/schemas/NewBodyPost'
el nombre del schema es `NewsBodyPost`

2022-08-16 22:51 UTC, ghnoob commented on routes/news.js
> + *   put:
el metodo es `get`

2022-08-16 22:51 UTC, ghnoob commented on routes/news.js
> + *    summary: Update a News (need JWT)
lo que hace es traer los comentarios de una noticia

2022-08-16 22:51 UTC, ghnoob commented on routes/news.js
> + *        description: all news
lo que trae es un array de comments, no de news

2022-08-16 22:51 UTC, ghnoob commented on routes/news.js
> + *                UnauthorizedError:
Aca tendria que decir `NotFoundError`, fijate que pasa lo mismo en varios lados

2022-08-16 22:51 UTC, ghnoob commented on routes/news.js
> + *                             $ref: '#/components/schemas/News'
falta documentar error de validacion

2022-08-16 22:55 UTC, ghnoob requested changes

2022-08-16 22:55 UTC, ghnoob commented on routes/news.js
> + *                $ref: '#/components/schemas/News'
aca lo que devuelve la response es en realidad un objeto que tiene una propiedad `news` con el array de news, y otra con la info de paginacion

2022-08-17 06:35 UTC, Samuel0023 commented on routes/news.js
> + *        required: true
En el schema de news dice que sí, va solo en el caso de Post

2022-08-17 09:14 UTC, Samuel0023 commented
Apa, me olvidé de subir el commit. subí cualquier cosa

2022-08-17 16:21 UTC, ghnoob approved these changes
te lo dejo como aprobado porque vi una pavada sola

2022-08-17 16:21 UTC, ghnoob commented on routes/news.js
> + *                [Error updating news] - [news/${id} - PUT]: Not found News
falto cambiar el mensaje en el ejemplo

2022-08-17 18:40 UTC, kamp3r approved these changes

2022-08-17 21:39 UTC, ignacioborraz approved these changes

2022-08-18 07:52 UTC, merged