Testimonials model and migrations
alkemyTech/OT246-Node pull request #12
Opened 2022-07-20 03:45 UTC by trabajoescueladesarrollo

Description

Fiels:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
image: VARCHAR NULLABLE
content: VARCHAR NULLABLE
timestamps y softDeletes
![image](https://user-images.githubusercontent.com/64031295/179891947-791343e9-83b3-4b62-98b9-c1bc2659ddc8.png)

2022-07-20 04:06 UTC, ghnoob requested changes
Restaurar `package-lock.json`. Recordar no agregarlo con `git add`

2022-07-20 04:06 UTC, ghnoob commented on database/migrations/20220719214208-create-testimonials.js
> +        type: Sequelize.STRING
```js
type: Sequelize.STRING,
allowNull: false
```
hacer lo mismo en el archivo del modelo

2022-07-20 04:06 UTC, ghnoob commented on database/migrations/20220719214208-create-testimonials.js
> +        allowNull: false,
```js
allowNull: true
```
este valor va a ser `null`, a menos que el registro se elimine

2022-07-20 04:06 UTC, ghnoob commented on database/models/testimonials.js
> +  class testimonials extends Model {
```js
class Testimonial extends Model {
```
los nombres de clases deberían estar en singular y empezar con una letra mayuscula

2022-07-20 04:06 UTC, ghnoob commented on database/models/testimonials.js
> +    modelName: 'testimonials',
```js
modelName: 'Testimonial'
```
para que sea consistente con la corrección de arriba

tambien agregar
```js
paranoid: true
```
para el softDelete

2022-07-20 04:06 UTC, ghnoob commented on database/migrations/20220719214208-create-testimonials.js
> +    await queryInterface.createTable('testimonials', {
```js
await queryInterface.createTable('Testimonials', {
```
ver correcciones en el archivo del modelo

2022-07-20 04:06 UTC, ghnoob commented on database/migrations/20220719214208-create-testimonials.js
> +    await queryInterface.dropTable('testimonials');
```js
await queryInterface.dropTable('Testimonials');
```

2022-07-20 12:21 UTC, gabodmc requested changes
Recordar hacer uso del sequelize CLI para no crear las tablas a mano
Al momento de correr el comando `npx sequelize model:generate` recordar pasarle la entidad en mayusculas, ej `npx sequelize model:generate --name Category`
Una vez que se crearon los dos archivos, indicar las propiedades de `allowNull: false` dentro de la migracion, y las timestamps/softdeletes dentro del model.

2022-07-20 13:13 UTC, trabajoescueladesarrollo commented
gracias rodri

El mié, 20 jul 2022 a las 6:07, Rodrigo Pietnechuk (<
***@***.***>) escribió:

> ***@***.**** requested changes on this pull request.
>
> Restaurar package-lock.json. Recordar no agregarlo con git add
> ------------------------------
>
> In database/migrations/20220719214208-create-testimonials.js
> <https://github.com/alkemyTech/OT246-Node/pull/12#discussion_r925149686>:
>
> > @@ -0,0 +1,40 @@
>
> +'use strict';
>
> +
>
> +const sequelize = require("sequelize");
>
> +
>
> +module.exports = {
>
> +  up: async (queryInterface, Sequelize) => {
>
> +    await queryInterface.createTable('testimonials', {
>
> +      id: {
>
> +        allowNull: false,
>
> +        autoIncrement: true,
>
> +        primaryKey: true,
>
> +        type: Sequelize.INTEGER
>
> +      },
>
> +      name: {
>
> +        type: Sequelize.STRING
>
>
> type: Sequelize.STRING,
> allowNull: false
>
> ------------------------------
>
> In database/migrations/20220719214208-create-testimonials.js
> <https://github.com/alkemyTech/OT246-Node/pull/12#discussion_r925150157>:
>
> > +      image: {
>
> +        type: Sequelize.STRING
>
> +      },
>
> +      content: {
>
> +        type: Sequelize.STRING
>
> +      },
>
> +      createdAt: {
>
> +        allowNull: false,
>
> +        type: Sequelize.DATE
>
> +      },
>
> +      updatedAt: {
>
> +        allowNull: false,
>
> +        type: Sequelize.DATE
>
> +      },
>
> +      deletedAt: {
>
> +        allowNull: false,
>
>
> allowNull: true
>
> este valor va a ser null, a menos que el registro se elimine
> ------------------------------
>
> In database/models/testimonials.js
> <https://github.com/alkemyTech/OT246-Node/pull/12#discussion_r925150590>:
>
> > @@ -0,0 +1,26 @@
>
> +'use strict';
>
> +const {
>
> +  Model
>
> +} = require('sequelize');
>
> +module.exports = (sequelize, DataTypes) => {
>
> +  class testimonials extends Model {
>
>
> class Testimonial extends Model {
>
> los nombres de clases deberían estar en singular y empezar con una letra
> mayuscula
> ------------------------------
>
> In database/models/testimonials.js
> <https://github.com/alkemyTech/OT246-Node/pull/12#discussion_r925151137>:
>
> > +     * Helper method for defining associations.
>
> +     * This method is not a part of Sequelize lifecycle.
>
> +     * The `models/index` file will call this method automatically.
>
> +     */
>
> +    static associate(models) {
>
> +      // define association here
>
> +    }
>
> +  };
>
> +  testimonials.init({
>
> +    name: DataTypes.STRING,
>
> +    image: DataTypes.STRING,
>
> +    content: DataTypes.STRING
>
> +  }, {
>
> +    timestamps:true,
>
> +    sequelize,
>
> +    modelName: 'testimonials',
>
>
> modelName: 'Testimonial'
>
> para que sea consistente con la corrección de arriba
> ------------------------------
>
> In database/migrations/20220719214208-create-testimonials.js
> <https://github.com/alkemyTech/OT246-Node/pull/12#discussion_r925153864>:
>
> > @@ -0,0 +1,40 @@
>
> +'use strict';
>
> +
>
> +const sequelize = require("sequelize");
>
> +
>
> +module.exports = {
>
> +  up: async (queryInterface, Sequelize) => {
>
> +    await queryInterface.createTable('testimonials', {
>
>
> await queryInterface.createTable('Testimonials', {
>
> ver correcciones en el archivo del modelo
> ------------------------------
>
> In database/migrations/20220719214208-create-testimonials.js
> <https://github.com/alkemyTech/OT246-Node/pull/12#discussion_r925153961>:
>
> > +      createdAt: {
>
> +        allowNull: false,
>
> +        type: Sequelize.DATE
>
> +      },
>
> +      updatedAt: {
>
> +        allowNull: false,
>
> +        type: Sequelize.DATE
>
> +      },
>
> +      deletedAt: {
>
> +        allowNull: false,
>
> +        type: Sequelize.DATE
>
> +      },
>
> +    });
>
> +  },
>
> +  down: async (queryInterface, Sequelize) => {
>
> +    await queryInterface.dropTable('testimonials');
>
>
> await queryInterface.dropTable('Testimonials');
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT246-Node/pull/12#pullrequestreview-1044383098>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APIQUPYGRWAVBTLLAFLUCVLVU53ONANCNFSM54CCIXCA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-20 13:15 UTC, trabajoescueladesarrollo commented
Gracias Gaby!!

El mié, 20 jul 2022 a las 14:21, Gabriel Martinez Corti (<
***@***.***>) escribió:

> ***@***.**** requested changes on this pull request.
>
> Recordar hacer uso del sequelize CLI para no crear las tablas a mano
> Al momento de correr el comando npx sequelize model:generate recordar
> pasarle la entidad en mayusculas, ej npx sequelize model:generate --name
> Category
> Una vez que se crearon los dos archivos, indicar las propiedades de allowNull:
> false dentro de la migracion, y las timestamps/softdeletes dentro del
> model.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT246-Node/pull/12#pullrequestreview-1044931820>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APIQUP7G45JELD4VL5ZEWQTVU7VMTANCNFSM54CCIXCA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-20 13:59 UTC, gabodmc requested changes
Quedaron muy bien los cambios. Le agregaria el paranoid true que sugeri en el file de models/testimonial.
Hay que revertir ese cambio del package-lock. No tiene que estar. Para que no aparezca se puede:

- Revertir el commit que lo subio
- Agarrar el archivo que esta en main y pegarlo en nuestra branch para que quede igual y no suba el cambio
- La menos elegante es borrar la branch, volverla a crear y subir solo los cambios que solicita la card

2022-07-20 13:59 UTC, gabodmc commented on database/models/testimonial.js
> +    timestamps:true,
paranoid: true

2022-07-20 22:26 UTC, gabodmc approved these changes

2022-07-20 23:31 UTC, kamp3r approved these changes
Buenisimo maria!

2022-07-20 23:31 UTC, bgalacho approved these changes

2022-07-21 00:05 UTC, Samuel0023 approved these changes
Exelente!!! 🥇

2022-07-21 16:05 UTC, ghnoob requested changes
falta aplicar [esta correccion](https://github.com/alkemyTech/OT246-Node/pull/12#discussion_r925640784) todavia, pero por lo demas esta bien

2022-07-22 19:49 UTC, ghnoob approved these changes
Aprobado! mergea cuando quieras

2022-07-22 19:51 UTC, merged