[USER-DELETE] create an user delete endpoint
alkemyTech/OT246-Node pull request #20
Opened 2022-07-20 21:02 UTC by Samuel0023

Evidence
![image](https://user-images.githubusercontent.com/38141029/180081006-d107a3e3-fede-4193-8e91-0afd0685a05a.png)

example:
![image](https://user-images.githubusercontent.com/38141029/180081455-f56a2601-d6e7-4ff3-afe6-0c6c4102735b.png)

2022-07-20 22:47 UTC, gabodmc requested changes
Va bien, solo unos cambios

2022-07-20 22:47 UTC, gabodmc commented on controllers/users.js
> +        body: await deleteUserById(id),
aplicar las correcciones que hablamos en la daily

2022-07-20 22:47 UTC, gabodmc commented on services/users.js
> +/**
No documenten (por ahora) las funciones

2022-07-21 14:53 UTC, tomasignacioc commented on controllers/users.js
> +        `[Error retrieving users] - [users - DELETE]: ${err.message}`,
Para mi está perfecto todo, pero acá no debería decir ` [Error removing user] ...` en lugar de  ` [Error retrieving users] ...` ?

2022-07-21 15:08 UTC, Samuel0023 commented on controllers/users.js
> +        `[Error retrieving users] - [users - DELETE]: ${err.message}`,
listo 👍🏽

2022-07-21 15:36 UTC, kamp3r approved these changes
Perfecto samu!
Quedo todo excelente! 💯

2022-07-21 15:37 UTC, gabodmc requested changes
Esta bastante bien. Solo unos cambios

2022-07-21 15:37 UTC, gabodmc commented on controllers/users.js
> +<<<<<<< HEAD
Guarda que quedaron lineas del merge. Hay que acomodar esto

2022-07-21 15:37 UTC, gabodmc commented on controllers/users.js
>    deleteById: catchAsync(async (req, res, next) => {
el metodo es destroy:

2022-07-21 16:19 UTC, Samuel0023 commented on controllers/users.js
> +<<<<<<< HEAD
consulta, que commit estas viendo?

2022-07-21 16:19 UTC, Samuel0023 commented on controllers/users.js
>    deleteById: catchAsync(async (req, res, next) => {
corregido

2022-07-21 16:38 UTC, gabodmc commented on controllers/users.js
> +        message: 'OK',
message: 'user successfuly deleted' o algo mas descriptivo

2022-07-21 16:38 UTC, gabodmc commented on controllers/users.js
> +<<<<<<< HEAD
Evidentemente me quedo algo cacheado. No le prestes atencion a esto

2022-07-21 17:43 UTC, ignacioborraz approved these changes
todo bem!

2022-07-21 17:45 UTC, ghnoob commented on database/models/user.js
> -    deletedAt: DataTypes.STRING
si se cambia el tipo de dato aca no habria que hacer otra migracion?
ademas veniamos usando DATE en vez de DATEONLY, no se si le cambiará algo

2022-07-21 18:14 UTC, Samuel0023 commented on database/models/user.js
> -    deletedAt: DataTypes.STRING
si, justo lo comunique en la anterior daily

2022-07-21 18:24 UTC, Samuel0023 commented on controllers/users.js
> +        message: 'OK',
![image](https://user-images.githubusercontent.com/38141029/180286336-66b47c29-8240-4db0-8b8f-42d01727ea7f.png)
no es suficiente con este return ???

2022-07-21 19:26 UTC, gabodmc approved these changes

2022-07-21 19:26 UTC, gabodmc commented on controllers/users.js
> +        message: 'OK',
Es mas por una normalizacion que otra cosa. Fijate que en la mayoria de endpoints le estan indicando un message

2022-07-21 20:04 UTC, Samuel0023 commented on controllers/users.js
> +        message: 'OK',
ok, perfecto. Ahí realizo el cambio

2022-07-21 20:08 UTC, merged