[ENDPOINT] GET /categories/public OT246-41 (fixed names)
alkemyTech/OT246-Node pull request #22
Opened 2022-07-21 12:03 UTC by ignacioborraz

fixed names
![image](https://user-images.githubusercontent.com/95113020/180209186-e9df410d-187d-4ef0-ae5f-edcb5aa9886d.png)

2022-07-21 14:37 UTC, tomasignacioc approved these changes
clarisimo

2022-07-21 15:04 UTC, ghnoob requested changes

2022-07-21 15:04 UTC, ghnoob commented on services/categories.js
> -exports.get = async () => {
yo lo llamaria `getCategories` por `getList` es demasiado generico

2022-07-21 17:41 UTC, ignacioborraz commented on services/categories.js
> -exports.get = async () => {
listorti!

2022-07-21 17:51 UTC, kamp3r approved these changes
Ahora si igna!
Vamos 🦾

2022-07-21 17:51 UTC, kamp3r commented on services/categories.js
> +exports.getList = async () => {
Lo modificaria por getCategories para que siga la linea de los demas PR. (no me odies)

2022-07-21 23:06 UTC, ghnoob approved these changes
Buena corrección!

2022-07-22 00:43 UTC, gabodmc approved these changes
Bien!

2022-07-22 01:45 UTC, merged