[MIDDLEWARE] - Verification Admin user
alkemyTech/OT246-Node pull request #23
Opened 2022-07-21 16:58 UTC by tomasignacioc

Ref: [OT246-27](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT246/boards/336?modal=detail&selectedIssue=OT246-27)

### Description:

COMO usuario administrador
QUIERO restringir el acceso a cierto contenido
PARA mantener los datos protegidos 

Criterios de aceptación:
Deberá verificar el campo roleId, y permitir continuar si el usuario tiene rol correspondiente a administrador

### Evidence:

![image](https://user-images.githubusercontent.com/83353643/180270639-05276cee-7170-4928-9e18-df51a2ed07a7.png)

![image](https://user-images.githubusercontent.com/83353643/180270805-3c25ee1f-20d4-44b9-989b-a4110fa0a865.png)
![image](https://user-images.githubusercontent.com/83353643/180270863-15d3907c-28da-48c7-b0ed-f98013c4e7ad.png)

2022-07-21 23:08 UTC, ghnoob requested changes

2022-07-21 23:08 UTC, ghnoob commented on middlewares/adminVerification.js
> +      throw new ErrorObject('Unauthorized', 403)
Poner mensaje mas específico

2022-07-22 00:42 UTC, gabodmc requested changes
Solo unos cambios

2022-07-22 00:42 UTC, gabodmc commented on middlewares/adminVerification.js
> +    const { id } = req.params
Aca le tiene que llegar el roleid y evaluarlo. No hay que buscarlo de nuevo en la db

2022-07-25 01:16 UTC, Samuel0023 commented on middlewares/adminVerification.js
> +exports.adminVerification = async (req, res, next) => {
no estaria bueno cambiar el nombre de la funcion a 
`isUserAdmin = async ...`
🤔 ??

2022-07-26 22:01 UTC, tomasignacioc commented on middlewares/adminVerification.js
> +exports.adminVerification = async (req, res, next) => {
dale, lo cambio

2022-07-27 12:58 UTC, ignacioborraz reviewed
@tomasignacioc pudiste hacer los cambios?
asi ya agregamos tu middle y corregimos nuestros avances!

2022-07-27 17:49 UTC, tomasignacioc commented
> @tomasignacioc pudiste hacer los cambios? asi ya agregamos tu middle y corregimos nuestros avances!

listo

2022-07-27 18:04 UTC, kamp3r approved these changes
Excelentes cambios tomi!

2022-07-27 20:05 UTC, ghnoob commented on middlewares/adminVerification.js
> +    const { roleId } = req.body
no tendria que llegar desde el token el roleId?

2022-07-27 20:05 UTC, gabodmc approved these changes

2022-07-27 21:42 UTC, ghnoob approved these changes

2022-07-27 22:24 UTC, kamp3r approved these changes

2022-07-27 23:56 UTC, merged