[SERVICE] Welcome email sending OT246-31
alkemyTech/OT246-Node pull request #30
Opened 2022-07-23 03:00 UTC by Samuel0023

AS user
I WANT to see a welcome email when I register
TO make sure the registration happened correctly.

## Criteria of acceptance:

- Use the send email service and welcome template to programmatically send an email when a user signs up, to the email you provided at registration

## Evidence 
![Opera Snapshot_2022-07-22_234422_mail google com](https://user-images.githubusercontent.com/38141029/180588031-d8147aff-e43b-43d0-b490-d8249aaf024e.png)

# path :  {{url}}/auth/register
![image](https://user-images.githubusercontent.com/38141029/180588074-24d5b726-5d3f-4941-9835-65df989c3985.png)

2022-07-23 03:09 UTC, Samuel0023 commented on controllers/users.js
> +      await sendMail(newUser.email, 'successful user registration', idTemplate, dynamicTemplateData)
decidí utilizar el  idTemplate, usando directamente el servicio de sendGrid para poder usarlo de manera dinamica.

2022-07-23 15:10 UTC, gabodmc requested changes
Esta muy bien! Solo una correccion

2022-07-23 15:10 UTC, gabodmc commented on controllers/users.js
> +
esto no va en el controller, iria en el servicio

2022-07-25 00:17 UTC, Samuel0023 commented on controllers/users.js
> +
entonces tendria que mandar como parametro algun indicado para que me mencione que tipo de mail va a mandar; para asi poder usar su template corespondiente?
![image](https://user-images.githubusercontent.com/38141029/180672013-89d34432-a0ea-43a7-9345-4c92ea6c3e33.png)

2022-07-25 02:40 UTC, Samuel0023 commented on controllers/users.js
> +
![image](https://user-images.githubusercontent.com/38141029/180682265-99ebb442-5151-4090-ab44-4ed842cf8e5a.png)

2022-07-25 13:40 UTC, gabodmc approved these changes

2022-07-25 15:08 UTC, ghnoob approved these changes
Buen pr samu!

2022-07-25 16:56 UTC, kamp3r approved these changes
Excelente samu, a mergear

2022-07-25 17:36 UTC, merged