[ENDPOINT] Update User Endpoint - OT246-35
alkemyTech/OT246-Node pull request #31
Opened 2022-07-23 07:04 UTC by kamp3r

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT246/boards/336?modal=detail&selectedIssue=OT246-35

AS user
I WANT TO UPDATE MY DATA
TO modify my profile

Criteria of acceptance:
PATCH to /users/:id. In the event that the user does not exist, it will return a 404 error.

### EVIDENCE

if send empty body
![test9](https://user-images.githubusercontent.com/85527959/180594377-9e4eb2a1-6b80-41b9-9dbe-18739715b85f.png)

if user not found
![test10](https://user-images.githubusercontent.com/85527959/180594383-3bf072b7-0bcb-4c3a-b5a7-9ab038c61596.png)

if body fields not pass validation send a specific error on the field
![test11](https://user-images.githubusercontent.com/85527959/180594410-594967ab-c15a-4f27-b810-9f80d7872ec9.png)

this endpoint and services ONLY UPDATE fields sended in the body request, if the field is empty or not sended, that fields not be updated
![test13](https://user-images.githubusercontent.com/85527959/180594458-43cb5b11-386f-49c4-b98c-1c7d928be599.png)

2022-07-23 15:12 UTC, gabodmc requested changes
En lineas generales esta bien, solo unos cambios

2022-07-23 15:12 UTC, gabodmc commented on controllers/users.js
> +    } = req
esta destructuracion te esta robando muchas lineas y se te vuelve repetitiva porque lo tenes tambien en el servicio

2022-07-23 15:12 UTC, gabodmc commented on schemas/update.js
> +module.exports = { updateBody }
este schema no esta solicitado en el scope de la tarea

2022-07-23 23:45 UTC, gabodmc approved these changes
Esta muy bien. Se que la card dice patch, pero tal vez usaria put y al controller le pondria "put" en lugar de "update". Es sugerencia, no es mandatorio

2022-07-24 01:13 UTC, bgalacho approved these changes
Excelente Martín! Seguí así! :rocket:

2022-07-24 01:35 UTC, ignacioborraz approved these changes
que codigo mas lindo! está aprobadisimo!

2022-07-24 01:36 UTC, merged