[ ENDPOINT  ] Authentication Endpoint OT246-25
alkemyTech/OT246-Node pull request #32
Opened 2022-07-24 21:27 UTC by MRobertaMendoza

AS user
I WANT to log into the system
TO access its functionalities

Criteria of acceptance:

A request of type POST /auth/login must be made

The sending of the email and password fields in the request must be validated, and the password must be decrypted to authenticate

Validate email and password on request

Check if there is a user with the requested email

If exists, compare encrypted password with password sent on request

Return the user if it exists and the password is valid, if an error occurs, return {ok: false} 
### Evidence
![image](https://user-images.githubusercontent.com/64031295/180666505-1fb3e24a-226c-4060-b796-6e7b9aae34d1.png)

2022-07-24 21:53 UTC, ignacioborraz reviewed
corregir los conflictos por favor!

2022-07-24 21:53 UTC, ignacioborraz commented on controllers/users.js
> +        `[Error registering account] - [auth/register- POST]: ${error.message}`,
este es el controlador de rodri
este cambio tenés que revertirlo agregando el espacio en la línea 34

2022-07-24 22:19 UTC, ghnoob requested changes
Te dejo un par de correcciones

2022-07-24 22:19 UTC, ghnoob commented on services/users.js
> +      throw new ErrorObject('Credentials not validat', 404)
el codigo tendria que ser 401

2022-07-24 22:19 UTC, ghnoob commented on services/users.js
> +    const token = generateToken(user.dataValues)
antes de generar el token tendrias que sacar la contraseña. no es buena practica guardar contraseñas en tokens

2022-07-24 22:19 UTC, ghnoob commented on schemas/login.js
> +    isStrongPassword: { errorMessage: 'Must be a strong password' },
me parece que cuando te logeas no seria necesario validar que sea una contraseña fuerte

2022-07-24 22:19 UTC, ghnoob commented on controllers/users.js
> +        code: 201,
de codigo le pondria 200 porque no se crea ningun recurso

2022-07-24 22:26 UTC, ignacioborraz commented on services/users.js
> +    const token = generateToken(user.dataValues)
me parece que entiendo tu acotación...
te referis a generar el token como menos datos que dataValues? onda solo con user.dataValues.email por ejemplo?

2022-07-25 01:09 UTC, Samuel0023 commented on services/users.js
> +    const token = generateToken(user.dataValues)
yo colocaría algo así:
`user.getDataValue('id_user')` 
porque lo único que quiero verificar es la existencia de dicho usuario. 
Por seguridad me parece incensario guardar TODOS los campos de un usuario, lo malo es que amerita más accesos a la DB si es que necesitáramos más info, pero como no nos lo piden...

2022-07-25 01:12 UTC, Samuel0023 requested changes
corregir los conflictos de merge 🥺 !!!

2022-07-25 01:47 UTC, ignacioborraz submitted a review, later dismissed

2022-07-25 01:47 UTC, ignacioborraz commented on controllers/users.js
> +      req.headers.authorization = `Bearer ${token}`
@gabodmc no pudimos setear esto: como se hace?

2022-07-25 08:48 UTC, Samuel0023 commented
> corregir los conflictos de merge 🥺 !!!

2022-07-25 13:38 UTC, gabodmc approved these changes

2022-07-25 13:38 UTC, gabodmc commented on controllers/users.js
> +      req.headers.authorization = `Bearer ${token}`
Generar el toquen seria del servicio, no del controlador

2022-07-25 13:39 UTC, gabodmc requested changes
Esta todo muy bien. Solo seria sacar esa linea del req.headers

2022-07-25 17:18 UTC, ghnoob approved these changes
Perfecto! Dejo una sola sugerencia

2022-07-25 17:18 UTC, ghnoob commented on routes/auth.js
> +const { login } = require('../controllers/users')
un unico cambio muy tonto de estilo que haria seria hacer este import junto con el de la linea de arriba, porque en las dos lineas se esta importando el mismo archivo

2022-07-25 18:33 UTC, MRobertaMendoza commented on routes/auth.js
> +const { login } = require('../controllers/users')
te razon, no me di cuenta...ahi lo modifico

2022-07-25 19:16 UTC, ghnoob approved these changes

2022-07-25 20:35 UTC, gabodmc approved these changes

2022-07-25 20:44 UTC, Samuel0023 approved these changes

2022-07-25 20:44 UTC, Samuel0023 commented on services/users.js
> +    const token = generateToken({ email: user.dataValues.email })
sé que no afecta la funcionalidad del sistema, pero no deberías cambiar el nombre del parámetro a recibir en dicha función??  osea se envia un (user.mail) pero se recibe (user). Y sigo pensando que estaría bueno enviar el, id, en vez del mail. Pero bueno... solo eso, todo lo demás genial 👍🏽

2022-07-25 20:44 UTC, Samuel0023 commented on services/users.js
> +    const token = generateToken({ email: user.dataValues.email })
![image](https://user-images.githubusercontent.com/38141029/180683691-b0ad76ad-1b83-4f8f-8dce-46996f9df40b.png)

2022-07-25 20:44 UTC, Samuel0023 commented on services/users.js
> +    const token = generateToken({ email: user.dataValues.email })
igual es tema de legibilidad del codigo 🤔

2022-07-25 20:44 UTC, Samuel0023 commented on controllers/users.js
> +      req.headers.authorization = `Bearer ${token}`
req.headers["authorization"] = `Bearer ${token}`  

creo que es algo asi... igual no estoy tan seguro

2022-07-25 21:36 UTC, ghnoob commented on services/users.js
> +    const token = generateToken({ email: user.dataValues.email })
> sé que no afecta la funcionalidad del sistema, pero no deberías cambiar el nombre del parámetro a recibir en dicha función?? osea se envia un (user.mail) pero se recibe (user). Y sigo pensando que estaría bueno enviar el, id, en vez del mail. Pero bueno... solo eso, todo lo demás genial 👍🏽

tal vez ambos

2022-07-25 22:11 UTC, merged