[Service] Support for Amazon S3 file management
alkemyTech/OT246-Node pull request #35
Opened 2022-07-25 22:00 UTC by bgalacho

**Descripción:**

COMO usuario administrador
QUIERO subir imágenes en el sistema
PARA mejorar la comunicación

Criterios de aceptación:
Se deberá vincular el servicio para manejo de archivos Amazon S3, a través de su SDK para Node.js. El mismo se utilizará posteriormente para campos de diferentes entidades, como la foto de perfil del usuario, logo de ONG, imágenes del blog y demás, por lo que debe crearse un servicio reutilizable para el manejo de archivos.

2022-07-25 23:05 UTC, ghnoob requested changes
- revertir el lockfile
- cambiar los exports de es6 por los de commonjs

2022-07-26 01:23 UTC, gabodmc requested changes
Esta muy bien. Solo unos cambios.
Ademas, recordar no subir cambios del package-lock.

2022-07-26 01:23 UTC, gabodmc commented on services/amazonS3.js
> +}
exportar como modulos para seguir el flujo de trabajo que ya se viene utilizando.

2022-07-26 16:30 UTC, gabodmc approved these changes

2022-07-26 16:50 UTC, kamp3r approved these changes
Excelentes cambios bren!

2022-07-26 16:50 UTC, kamp3r commented on services/amazonS3.js
> +export function uploadFileContents(fileName, fileContents) {
Modificar los export, ya que no son compatibles con la sintaxis de common js
Esta sintaxis es de module js

2022-07-26 16:55 UTC, ghnoob approved these changes
Buenos cambios!

2022-07-26 17:27 UTC, merged