[ENDPOINT] Endpoint Detail News OT246-46
alkemyTech/OT246-Node pull request #40
Opened 2022-07-26 22:43 UTC by kamp3r

AS admin user
I WANT to see the details of a novelty
TO be able to report content updates

Criteria of acceptance:
GET to /news/:id . It will show all the fields of an entry based on the id sent by parameter.

### EVIDENCE

![test21](https://user-images.githubusercontent.com/85527959/181124714-0295fc9d-200c-4b26-aa6e-f213a11a8d00.png)

![test22](https://user-images.githubusercontent.com/85527959/181124728-26be34bb-ecd2-42bc-8538-76f42cc7b852.png)

2022-07-26 23:42 UTC, ghnoob requested changes
Revisar que este pr se esta mezclando con el otro que hiciste hoy

2022-07-26 23:42 UTC, ghnoob commented on routes/news.js
> +router.get('/:id', authUser, getById)
esta seria una ruta publica. cualquiera tendria que poder leer las noticias

2022-07-26 23:50 UTC, kamp3r commented on routes/news.js
> +router.get('/:id', authUser, getById)
No, es solo para admin. solo que falta ese PR.
Por otro lado esta solucionado el tema de el organization schema

2022-07-27 02:22 UTC, gabodmc approved these changes

2022-07-27 03:34 UTC, ghnoob approved these changes

2022-07-27 05:06 UTC, Samuel0023 approved these changes

2022-07-27 05:10 UTC, merged