[ENDPOINT] POST /news OT246 47
alkemyTech/OT246-Node pull request #41
Opened 2022-07-26 23:43 UTC by ignacioborraz

AS admin user
I WANT to add a novelty in the system
TO be able to inform the News of the NGO

Criteria of acceptance:
POST /news - You must validate the existence of the submitted fields, to store the record in the news table. Before storing it, you will need to assign the type column to it with the value "news".

![image](https://user-images.githubusercontent.com/95113020/181130792-efd4b430-a2d5-412b-9d84-1d480075cd43.png)

2022-07-26 23:47 UTC, ghnoob commented on schemas/news.js
> +    isOptional: true,
la propiedad es `optional`

2022-07-26 23:47 UTC, ghnoob commented on schemas/news.js
> +    isAlphaWithSpace: { errorMessage: 'Must contain alphabetic characters only' },
con esta propiedad @kamp3r tuvo problemas y tuvo que usar regex, fijate bien si anda

2022-07-26 23:47 UTC, ghnoob commented on services/news.js
> +      categoryId: 1,
por que esta hardcodeada la categoria?

2022-07-26 23:59 UTC, kamp3r commented on schemas/news.js
> +    isAlphaWithSpace: { errorMessage: 'Must contain alphabetic characters only' },
si le funciona es brujeria!

2022-07-27 01:29 UTC, ignacioborraz commented on services/news.js
> +      categoryId: 1,
esta hardcodeada como el rolId: 2
la categoryId: 1 se referencia con la categoria news que me pide

2022-07-27 01:30 UTC, ignacioborraz commented on schemas/news.js
> +    isAlphaWithSpace: { errorMessage: 'Must contain alphabetic characters only' },
la evidencia que subi está hecha con esto! jajajaja

2022-07-27 01:38 UTC, ignacioborraz commented on schemas/news.js
> +    isOptional: true,
done

2022-07-27 01:41 UTC, ghnoob commented on services/news.js
> +      categoryId: 1,
ah listo, no sabia como eran las categorias

2022-07-27 02:07 UTC, ghnoob commented on schemas/news.js
> +    isAlphaWithSpace: { errorMessage: 'Must contain alphabetic characters only' },
la cosola me esta tirando esto, dice que el validador ese no existe
![image](https://user-images.githubusercontent.com/58740322/181144837-8313429f-974d-43f0-ba05-e4f12a8651a2.png)

2022-07-27 02:21 UTC, gabodmc approved these changes

2022-07-27 02:21 UTC, gabodmc commented on schemas/news.js
> +    isAlphaWithSpace: { errorMessage: 'Must contain alphabetic characters only' },
No se compliquen con las validaciones.

2022-07-27 12:12 UTC, ignacioborraz commented on schemas/news.js
> +    isAlphaWithSpace: { errorMessage: 'Must contain alphabetic characters only' },
ya saque las que se nos complican!

2022-07-27 12:13 UTC, ignacioborraz commented
acabo de cambiar la evidencia
cambié el modelo de news tal y como me pidieron!

2022-07-27 16:44 UTC, kamp3r requested changes

2022-07-27 16:44 UTC, kamp3r commented on routes/news.js
> +const { post } = require('../controllers/news')
Esta linea esta de mas, deberias hacer la importacion de post, dentro de la misma desestructuracion que getById

2022-07-27 16:44 UTC, kamp3r commented on schemas/news.js
> +    notEmpty: { errorMessage: 'Must not be empty' },
Agregaria regEx para no permitir que los nombres puedan ser cualquier cosa, lo mismo haria en content

2022-07-27 17:23 UTC, ghnoob commented on schemas/news.js
> +    notEmpty: { errorMessage: 'Must not be empty' },
No me parece necesario eso. Esta bien hacer algunas validaciones, como que no falte o no este vacío el campo, pero tampoco hace falta ser tan exigente. Pensando en el uso que se le va a dar al endpoint, no tendria sentido que un admin se ponga a publicar cualquier cosa en el sitio porque sí.

2022-07-27 17:25 UTC, ghnoob requested changes

2022-07-27 17:25 UTC, ghnoob commented on database/migrations/20220720171428-create-new.js
> +      },
Me parece que tendrias que crear una migracion nueva para agregar una columna en vez de editar la vieja, porque si no se hace en una base de datos nueva/vacía, la migracion vieja no se aplicaría.

2022-07-27 17:33 UTC, kamp3r approved these changes

2022-07-27 18:59 UTC, ghnoob requested changes
Unas pequeñas correciones

2022-07-27 18:59 UTC, ghnoob commented on schemas/news.js
> +  },
agregar una validacion de que `categoryId` sea un entero

2022-07-27 18:59 UTC, ghnoob commented on services/news.js
> +  } catch (err) {
le agragaria el manejo de error por si el categoryId que te pasan no existe en la db, por ejemplo
```js
const { ForeignKeyConstraintError } = require('sequelize')

// resto del codigo

if (err instanceof ForeignKeyConstraintError) {
  throw new ErrorObject(`Category with id ${categoryId} does not exist`, 400)
}
```

2022-07-27 21:39 UTC, ghnoob approved these changes

2022-07-27 21:48 UTC, merged