[SERVICE] service to upload images OT246-40
alkemyTech/OT246-Node pull request #42
Opened 2022-07-27 00:27 UTC by Samuel0023

AS admin user
I WANT to upload images in the system
TO improve communication

Criteria of acceptance:
It should be integrated with existing methods that handle images. It will take care of storing an image in Amazon and returning the absolute path to the bucket

2022-07-27 02:15 UTC, gabodmc requested changes
Dejo este comentario para que me lleguen las notificaciones cuando haya los cambios requeridos.

2022-07-27 12:33 UTC, gabodmc requested changes
Faltaria algo de evidencia en el pr

2022-07-27 19:49 UTC, gabodmc requested changes
Lo veo bien, solo unos cambios

2022-07-27 19:49 UTC, gabodmc commented on services/uploadFile.js
> +  bucketName: process.env.AWS_BUCKET_NAME,
Estas credenciales ya estan en el servicio, para que repetirlas?

2022-07-27 22:24 UTC, kamp3r approved these changes

2022-07-27 22:34 UTC, bgalacho approved these changes

2022-07-27 23:26 UTC, Samuel0023 commented on services/uploadFile.js
> +  bucketName: process.env.AWS_BUCKET_NAME,
En si las guardo asi, para no tener que colocar ${process.env...} al momento de retornar la ruta absoluta al bucket, ademas al momento de crear el PutObjectCommand(). Se debe pasar él bucket.name como parte del constructor.

La unica variable de entorno que repito tanto en amazonS3.js como en uploadFile.js es el de AWS_REGION

2022-07-28 14:12 UTC, gabodmc approved these changes

2022-07-28 14:24 UTC, ghnoob approved these changes
joya

2022-07-28 16:39 UTC, merged