[ENDPOINT] PUT /activities/:id
alkemyTech/OT246-Node pull request #55
Opened 2022-07-28 16:50 UTC by tomasignacioc

# Descripción

COMO usuario administrador
QUIERO actualizar una actividad existente
PARA mantener la información actualizada

## Criterios de aceptación:
PUT /activities/:id - Deberá validar que la actividad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizarla y devolverla con los datos actualizados

## Evidencia

### - caso de éxito

![image](https://user-images.githubusercontent.com/83353643/181593147-96124710-0155-4710-afa3-9b700e4d1454.png)

### - caso en que no exista la actividad

![image](https://user-images.githubusercontent.com/83353643/181593418-05b3059f-1235-49d0-be17-757f6e2c6181.png)

### - caso en que no seas administrador de la página

![image](https://user-images.githubusercontent.com/83353643/181593545-8ae1c71d-384f-4c25-82b3-e9b56c2f10fb.png)

2022-07-28 17:15 UTC, ghnoob requested changes
Algunas sugerencias

2022-07-28 17:15 UTC, ghnoob commented on services/activities.js
> +exports.updateActivity = async (id, name, content, image) => {
name, content e image se los pasaria en un mismo objeto porque son todas propiedades que vienen del body

2022-07-28 17:15 UTC, ghnoob commented on schemas/activities.js
> +    optional: false,
a los 3 optional ponelos como true porque si no estas obligando a actualizar siempre todos los campos

2022-07-28 17:15 UTC, ghnoob commented on controllers/activities.js
> +        code: 201,
para los updates todos estamos usando status code 200

2022-07-28 18:27 UTC, tomasignacioc commented on controllers/activities.js
> +        code: 201,
perfecto

2022-07-28 18:27 UTC, tomasignacioc commented on schemas/activities.js
> +    optional: false,
gracias! se me pasó

2022-07-28 18:32 UTC, tomasignacioc commented on services/activities.js
> +exports.updateActivity = async (id, name, content, image) => {
vos decis para que quede un codigo menos verboso?

2022-07-28 18:53 UTC, ghnoob approved these changes
buenas correcciones

2022-07-28 18:54 UTC, tomasignacioc commented
> buenas correcciones

gracias tigre

2022-07-28 19:19 UTC, ghnoob commented on services/activities.js
> +exports.updateActivity = async (id, name, content, image) => {
se considera codigo sucio tener una funcion con muchos argumentos.
pensa que te tenes que acordar el orden, pero si se lo pasas como objeto te olvidas de eso
mas en un caso como este que los parametros son todos opcionales

https://refactoring.guru/es/smells/long-parameter-list

2022-07-28 19:29 UTC, tomasignacioc commented on services/activities.js
> +exports.updateActivity = async (id, name, content, image) => {
muy buena data !

2022-07-28 20:48 UTC, kamp3r approved these changes

2022-07-29 02:35 UTC, tomasignacioc commented on routes/activities.js
> +router.put('/:id', authUser, validateSchema(activityBodyPut), put)
Revisando otros PR's me surge la duda si deberíamos agregar el middleware "isAdminUser" a estas 2 rutas

2022-07-29 14:19 UTC, gabodmc requested changes
Esta todo perfecto. Solo un minimo cambio y una sugerencia

2022-07-29 14:19 UTC, gabodmc commented on routes/activities.js
> +router.put('/:id', authUser, validateSchema(activityBodyPut), put)
Si, a esta ruta agregarle el isAdmin. La otra tambien le falta, pero te sacaria del scope de la card. Despues las van a acomodar

2022-07-29 14:19 UTC, gabodmc commented on services/activities.js
> +      },
ojo con estas identaciones

2022-07-29 18:12 UTC, tomasignacioc commented on services/activities.js
> +      },
perdon si suena mal la pregunta, pero qué tienen? está muy espaciado?

2022-07-30 20:11 UTC, kamp3r approved these changes
Aprobado señor

2022-07-30 20:20 UTC, ignacioborraz approved these changes

2022-07-31 15:00 UTC, gabodmc approved these changes

2022-08-01 13:42 UTC, merged