[Organizations] Modified endpoint organizations with new fields
alkemyTech/OT246-Node pull request #64
Opened 2022-07-29 18:32 UTC by bgalacho

**Descripción**

COMO usuario
QUIERO ver los links de las redes sociales al entrar a la página
PARA poder acceder a ellas.

Criterios de aceptación:

Al devolver los datos en el endpoint de datos públicos, agregar los campos de redes sociales en la respuesta.

2022-07-29 23:13 UTC, ghnoob commented on schemas/organization.js
> +  },
mepa que esto no te lo pidio

2022-07-30 19:13 UTC, ignacioborraz commented on schemas/organization.js
> +  },
validamos datos en el PR de creacion de este endpoint no?
no lo veo mal...

2022-07-30 19:14 UTC, ignacioborraz approved these changes

2022-07-31 14:56 UTC, gabodmc requested changes
Esta todo bien. Solo la correccion en el schema.

2022-07-31 14:56 UTC, gabodmc commented on schemas/organization.js
> +  },
Esto estaria fuera del scope

2022-08-01 15:31 UTC, ghnoob approved these changes

2022-08-01 21:01 UTC, gabodmc approved these changes

2022-08-01 22:09 UTC, merged