[ENDPOINT] need help! OT246-59
alkemyTech/OT246-Node pull request #67
Opened 2022-07-30 22:00 UTC by ignacioborraz

i'm a bit lost with this endpoint.
controller does not recognize req.body and i have this error:
![image](https://user-images.githubusercontent.com/95113020/181999922-dce24dbc-f9e5-4639-8dd4-6f8c98d3e857.png)

AS admin user
I WANT to be able to create Slides
TO add more information to the top of the page

Criteria of acceptance:
A POST /slide request must be made
You will receive the image to be stored in base 64. It must be decoded and stored in Amazon S3.
In the case of not receiving the order field, you must set it as the last one based on the existing ones (i haven't done this yet)

2022-08-01 04:50 UTC, kamp3r requested changes

2022-08-01 04:50 UTC, kamp3r commented on services/slides.js
> +  const imageUrl = uploadFile(image)
Creo que el error que estas teniendo es porque uploadFile, es una funcion asincronica. En la consola fijate que el estado de la promise es rejected. no se si sera solo eso, pero de momento el erro que veo es una promesa que no se resuelve

2022-08-01 05:54 UTC, Samuel0023 commented on services/slides.js
> +  const imageUrl = uploadFile(image)
No, el problema yace en que él no puede recibir el file desde el lado del cliente. Le aconsejé que consulte a Gabo si es posible agregar una dependencia para agilizar dicho trámite. Ej.: express-uploadFile, multer, etc.

2022-08-01 15:00 UTC, gabodmc commented on services/slides.js
> +  const imageUrl = uploadFile(image)
El pr esta bien, pero estan teniendo este problema porque el servicio que se creo de uploadImage esta mal. 
Tienen que correr un fix para que uploadfile haga la gestion del archivo. Pueden usar multer/fs o el express-uploadfile

2022-08-01 15:36 UTC, ignacioborraz commented on services/slides.js
> +  const imageUrl = uploadFile(image)
le acabo de agregar a mi servicio eso... como seria entonces?

2022-08-01 20:31 UTC, ghnoob approved these changes

2022-08-02 09:45 UTC, kamp3r approved these changes

2022-08-02 13:16 UTC, Samuel0023 approved these changes
Buenisimoo !!! 💯

2022-08-02 18:25 UTC, merged