[ENDPOINT] Creation Members
alkemyTech/OT246-Node pull request #70
Opened 2022-08-01 18:16 UTC by kamp3r

AS user
I WANT to create a member
TO update the information on the website.

Criteria of acceptance:
POST /members - You must validate that the name field is sent, and it is a string

### EVIDENCE

![OT10](https://user-images.githubusercontent.com/85527959/182214645-4dd16f30-aa57-4b48-9a79-98a301cb4ea1.png)

![OT11](https://user-images.githubusercontent.com/85527959/182214664-2948e51c-4dd5-4c9c-b2af-672dde8d2268.png)

2022-08-01 18:32 UTC, ignacioborraz approved these changes
yo hubiera metido todo adentro de users (al fin y al cabo los miembros son usuarios también no?)
de todas formas: guantanamera y dale pa lante!

2022-08-01 20:35 UTC, ghnoob requested changes
Me parece que te fuiste un poquitin del scope. Aunque si, en realidad habría que validar todos los campos, la card no te pide que lo hagas

2022-08-01 20:35 UTC, ghnoob commented on schemas/members.js
> +  },
la card solo te pidio que valides el name, no todo lo otro, aunque sea opcional

2022-08-01 21:45 UTC, ghnoob requested changes

2022-08-01 21:45 UTC, ghnoob commented on services/members.js
> +      linkedinUrl,
estos campos volalos porque los saco de la entidad

2022-08-01 21:45 UTC, ghnoob commented on services/members.js
> +      description,
este tambien

2022-08-02 16:03 UTC, ghnoob approved these changes

2022-08-03 01:16 UTC, gabodmc approved these changes

2022-08-03 01:51 UTC, merged