[Endpoint] Testimonials delete endpoint
alkemyTech/OT246-Node pull request #72
Opened 2022-08-01 23:19 UTC by bgalacho

**Descripción**
COMO usuario administrador
QUIERO eliminar Testimonios
PARA moderar los Testimonios y Novedades acerca de la ONG.

**Evidencia**
![Captura de pantalla de 2022-08-01 20-01-02](https://user-images.githubusercontent.com/85257382/182261103-8568ee77-b1fd-463d-a7c0-e51e77998179.png)
![Captura de pantalla de 2022-08-01 20-06-53](https://user-images.githubusercontent.com/85257382/182261115-a1350445-ac0b-4208-98b5-a77f8e32bc05.png)
![Captura de pantalla de 2022-08-01 20-07-21](https://user-images.githubusercontent.com/85257382/182261119-1c3330e9-05dd-402f-ba74-27389801dca2.png)

2022-08-02 02:28 UTC, ignacioborraz approved these changes
eliminemos todo por las dudas! jajajaja

2022-08-02 09:45 UTC, kamp3r approved these changes
Mas gente como mirtha

2022-08-02 15:19 UTC, ghnoob requested changes
Unos pequeños cambios en los mensajes asi coinciden con los estandares que hizo samu

2022-08-02 15:19 UTC, ghnoob commented on controllers/testimonials.js
> +        message: `Testimonial ${req.params.id} was deleted`,
Cambiaria el mensaje a `Testimonial successfully deleted`

2022-08-02 15:19 UTC, ghnoob commented on controllers/testimonials.js
> +        `[Error deleting testimonial] - [testimonials - DELETE /testimonial/${req.params.id}] - ${err.message}`,
cambiaría mensaje a `[Error deleting testimonial] - [testimonials/${req.params.id} - DELETE ]: ${err.message}`

2022-08-02 16:02 UTC, ghnoob approved these changes

2022-08-02 16:03 UTC, bgalacho commented on controllers/testimonials.js
> +        `[Error deleting testimonial] - [testimonials - DELETE /testimonial/${req.params.id}] - ${err.message}`,
Listo @ghnoob !

2022-08-03 01:15 UTC, gabodmc approved these changes

2022-08-03 01:46 UTC, merged