[ENDPOINT] - GET /members
alkemyTech/OT246-Node pull request #82
Opened 2022-08-03 16:03 UTC by tomasignacioc

# DESCRIPCION

COMO administrador
QUIERO listar los Miembros
PARA obtener información certera de los Miembros al día.

Criterios de aceptación:
GET /members - Devolverá todos los Miembros

# EVIDENCIA

caso de éxito

![image](https://user-images.githubusercontent.com/83353643/182655006-54910fff-1b5f-402e-b4b0-8320a7d450c2.png)

caso de fallo

![image](https://user-images.githubusercontent.com/83353643/182655697-edb2b765-2170-45f8-a90e-53740dd79e8a.png)

2022-08-03 17:23 UTC, ghnoob commented on routes/members.js
> +router.get('/', authUser, isUserAdmin, get)
se me hace medio raro que se pida admin para informacion que deberia ser publica pero por la forma que esta redactada la card no se que pide realmente

2022-08-03 17:39 UTC, gabodmc commented on routes/members.js
> +router.get('/', authUser, isUserAdmin, get)
Igual esta bien agregado. Como ya tienen middle de admin, y la card dice "como administrador", estaria bien que lo agreguen

2022-08-03 17:39 UTC, gabodmc approved these changes

2022-08-03 21:14 UTC, ghnoob approved these changes
Arregla los conflictos y fijate que con samu configuramos el middle de admin para que aplique automaticamente y el middle de authUser sin tener que poner los dos juntos
asi que en el router te tendria que quedar el de admin solo

2022-08-03 22:07 UTC, kamp3r approved these changes

2022-08-04 14:13 UTC, ignacioborraz approved these changes
10!

2022-08-04 15:40 UTC, tomasignacioc commented
> Arregla los conflictos y fijate que con samu configuramos el middle de admin para que aplique automaticamente y el middle de authUser sin tener que poner los dos juntos asi que en el router te tendria que quedar el de admin solo

fijate si ahi quedó mejor

2022-08-04 19:32 UTC, ghnoob requested changes
Volvete a mergear main
no se que paso pero se te cambiaron un monton de archivos

2022-08-04 20:40 UTC, ghnoob approved these changes

2022-08-04 20:41 UTC, merged