[Endpoint] Comments by news
alkemyTech/OT246-Node pull request #88
Opened 2022-08-04 20:43 UTC by bgalacho

Descripción

COMO usuario
QUIERO visualizar los Comentarios de un post
PARA obtener la información organizada

Criterios de aceptación:
GET /posts/:id/comments - Devolverá todos los Comentarios pertenecientes a un post

2022-08-04 21:08 UTC, ghnoob reviewed
No tendria que tirar un 404 si la novedad no existe?
para que la respesta sea consistente con la de `GET news/:id`

2022-08-05 13:32 UTC, gabodmc approved these changes
Solo un minimo comentario sumandome a lo de Rodri. Y recordar de subir la evidencia

2022-08-05 13:32 UTC, gabodmc commented on services/comments.js
> +    throw new ErrorObject(err.message, 500)
error 500 son para problemas del server. En este caso tendria que ser un 404.

2022-08-08 19:35 UTC, gabodmc approved these changes

2022-08-08 19:35 UTC, gabodmc requested changes

2022-08-08 19:35 UTC, gabodmc commented on services/comments.js
> +    throw new ErrorObject(err.message, err.statusCode || 500)
Sigo viendo el 500 en lugar de 404

2022-08-08 20:05 UTC, ghnoob commented on services/comments.js
> +    throw new ErrorObject(err.message, err.statusCode || 500)
fijate las lineas 20 y 21, ahi tendria que funcionar

2022-08-08 20:10 UTC, ghnoob approved these changes
Para mi esta bien

2022-08-08 20:15 UTC, bgalacho commented on services/comments.js
> +    throw new ErrorObject(err.message, err.statusCode || 500)
Pero si hardcodeo el 404, va a tirar 404 si hay error de conexión a base de datos. Como está ahora va a tirar 404 cuando no encuentra la noticia y otros códigos según la excepción con el 500 como predeterminado o le estoy errando en algún concepto?

2022-08-08 22:54 UTC, gabodmc approved these changes

2022-08-08 22:56 UTC, kamp3r approved these changes

2022-08-08 22:56 UTC, merged