[ENDPOINT]OT246-62
alkemyTech/OT246-Node pull request #89
Opened 2022-08-04 22:02 UTC by MRobertaMendoza

Description

AS user
I WANT to see Slides when I enter the page
TO be more informed about them

Criteria of acceptance:

In the public data endpoint of the Organization, the list of Slides ordered by the "order" field must be added.

The Slides will be those belonging to the Organization, based on the organization_id field that should correspond to the Organization that is being returned
EVIDENCE
![image](https://user-images.githubusercontent.com/64031295/182960354-22cf9b8c-eee4-46d3-bf6a-db4a4fd6a2fa.png)

2022-08-04 22:47 UTC, ghnoob requested changes
No tendrias que tocar los modelos, las migraciones o el package.json porque la card no te lo pide.
no commitear el lockfile

2022-08-04 22:47 UTC, ghnoob commented on services/organizations.js
> +    throw new ErrorObject(err.message || 500)
esto estaba bien antes
de ultima podes poner `err.message, err.statusCode || 500`

2022-08-04 22:47 UTC, ghnoob commented on services/organizations.js
> +        [Slide, 'imageUrl', 'DESC'],
la tendrias que ordenar por `order`, no por `imageUrl`
y ascendentemente

2022-08-05 00:19 UTC, MRobertaMendoza commented on services/organizations.js
> +        [Slide, 'imageUrl', 'DESC'],
tenes razon , lo estaba probando y me despues me olvide de cambiarlo..

2022-08-05 00:19 UTC, MRobertaMendoza commented on services/organizations.js
> +    throw new ErrorObject(err.message || 500)
ok

2022-08-05 00:58 UTC, MRobertaMendoza commented on services/organizations.js
> +        [Slide, 'imageUrl', 'DESC'],
![image](https://user-images.githubusercontent.com/64031295/182979583-f60e130b-5f8f-43c2-8a30-ba1418060d46.png)

2022-08-05 01:18 UTC, ghnoob requested changes
> No tendrias que tocar los modelos, las migraciones o el package.json porque la card no te lo pide. no commitear el lockfile

Recorda esto

2022-08-05 12:05 UTC, ignacioborraz commented on services/organizations.js
>      const result = await Organization.findOne({
El método que usaste te va a traer una sola slide (la última).
Usar findAll.

Por otro lado, entiendo que el modelo organization es para exclusivamente nuestra organizacion, pero leyendo el ticket creo que uno de los criterios de busqueda es que coincida el organizationId

Te falta el controlador y la ruta

2022-08-05 13:24 UTC, ghnoob commented on services/organizations.js
>      const result = await Organization.findOne({
no, lo que trae es una sola organizacion. slides trae todas, revisa la evidencia.
y al hacer el include con sequelize por abajo te hace un left join asi que siempre va a coincidir el id

2022-08-05 13:43 UTC, ghnoob requested changes
estos archivos te siguen apareciendo como modificados

![image](https://user-images.githubusercontent.com/58740322/183089769-e69fae61-84aa-4453-8353-4219cf047682.png)

2022-08-05 13:49 UTC, gabodmc requested changes
No modificar el package y package-lock. Hay que controlar bien los archivos que se estan subiendo antes de commitear y pushear.

El resto esta todo bien

2022-08-05 15:02 UTC, ghnoob approved these changes
me gusta

2022-08-05 15:11 UTC, Samuel0023 approved these changes
Buen pr!!!

2022-08-05 16:01 UTC, gabodmc approved these changes

2022-08-05 16:32 UTC, merged