[ENDPOINT] - PUT /comments/:id
alkemyTech/OT246-Node pull request #91
Opened 2022-08-05 18:55 UTC by tomasignacioc

# Descripción

COMO usuario
QUIERO actualizar un comentario propio
PARA mantener la información actualizada

Criterios de aceptación:
PUT /comments/:id - Deberá validar la existencia del comentario en base a su id. Solamente podrán editar un comentario el usuario que lo realizó o un administrador

# Evidencia

![image](https://user-images.githubusercontent.com/83353643/183142332-de32f32e-5164-43bb-9f70-f1114630af5a.png)

![image](https://user-images.githubusercontent.com/83353643/183142394-ff75b70a-153a-4a53-9c59-a87c07beedfc.png)

![image](https://user-images.githubusercontent.com/83353643/183142746-60b713e9-c3ae-48e3-bd2e-c2aab3fc9bd2.png)

![image](https://user-images.githubusercontent.com/83353643/183142879-f589dc9f-2215-4c77-8b5d-c5b77da1849a.png)

2022-08-05 20:58 UTC, ghnoob requested changes

2022-08-05 20:58 UTC, ghnoob commented on services/comments.js
> +    if (comment.dataValues.userId === userId) {
falta un OR que compruebe si es admin
creo que habia un middleware de ownership hecho pero para este endpoint no creo que sirva

2022-08-05 21:11 UTC, tomasignacioc commented on services/comments.js
> +    if (comment.dataValues.userId === userId) {
pase por alto esa parte, pense que con el middleware authUser alcanzaba, pero el tema es que asi como esta implementado un admin solo podria editar sus propios comentarios pero no podria moderar los demas

2022-08-06 00:10 UTC, ghnoob approved these changes
Esta bien. Dejo una sugerencia

2022-08-06 00:10 UTC, ghnoob commented on services/comments.js
> +exports.updateComment = async (id, body, userId, roleId) => {
tanto el id del usuario como el del rol se los pasaria en el mismo objeto porque pertenecen los dos al usuario

2022-08-08 19:23 UTC, gabodmc commented on services/comments.js
> +exports.updateComment = async (id, body, userId, roleId) => {
+1

2022-08-08 19:23 UTC, gabodmc approved these changes

2022-08-08 20:02 UTC, ignacioborraz approved these changes

2022-08-08 20:04 UTC, merged