[ENDPOINT] GET /testimonials OT246-88
alkemyTech/OT246-Node pull request #93
Opened 2022-08-05 20:54 UTC by ghnoob

## Descripcion

COMO usuario
QUIERO visualizar los resultados de Testimonios paginados
PARA aumentar la velocidad de respuesta

### Criterios de aceptación

Cuando se realice la petición para listar, los resultados deberán paginarse de a 10. En la respuesta, se deberán mostrar los resultados y las urls para la página anterior y siguiente (si corresponden). La página actual se obtendrá del parámetro de query ?page

## Evidencia

![image](https://user-images.githubusercontent.com/58740322/183160983-719f43f1-0d86-4cac-a083-cbaab54f94c2.png)

2022-08-08 17:15 UTC, ghnoob commented
La pongo como draft hasta que el refactor de samu este mergeado porque si no se va a romper

2022-08-08 21:04 UTC, ghnoob commented
Ya mergee main en esta rama y anda todo

2022-08-08 23:25 UTC, ignacioborraz approved these changes

2022-08-08 23:35 UTC, bgalacho approved these changes

2022-08-09 01:23 UTC, kamp3r approved these changes

2022-08-09 13:34 UTC, tomasignacioc approved these changes

2022-08-09 17:53 UTC, kamp3r requested changes

2022-08-09 17:53 UTC, kamp3r commented on routes/testimonials.js
> +router.get('/', get)
Estaria faltando el AuthUser, ya que solicita que sea como usuario

2022-08-09 21:36 UTC, gabodmc approved these changes

2022-08-09 22:09 UTC, kamp3r approved these changes

2022-08-09 23:31 UTC, merged