[SWAGGER INTERFACE] OT246-89
alkemyTech/OT246-Node pull request #95
Opened 2022-08-09 04:30 UTC by MRobertaMendoza

Description

AS a developer
I WANT to have a documentation of the API endpoints
TO have references of the operation of the system

Criteria of acceptance:

The Swagger library must be implemented to document the different endpoints of the project. When entering the /api/docs endpoint, the layout should be displayed. Additionally, add the possibility to implement the different schemas based on the method Comments of each controller.

EVIDENCE
![image](https://user-images.githubusercontent.com/64031295/183564418-10752c90-14eb-4f30-adc0-71845a51a838.png)

2022-08-09 21:30 UTC, gabodmc requested changes
Esta muy bien, solo un cambio pequeño

2022-08-09 21:30 UTC, gabodmc commented on app.js
> +app.use('/api/docs', swaggerUI.serve, swaggerUI.setup(swaggerJsDoc(specs)))
Hacer el llamado desde un archivo en el indexrouter como las demas rutas

2022-08-10 01:54 UTC, MRobertaMendoza commented on app.js
> +app.use('/api/docs', swaggerUI.serve, swaggerUI.setup(swaggerJsDoc(specs)))
ok...ahí lo corrijo..

2022-08-10 04:01 UTC, ghnoob approved these changes

2022-08-10 04:01 UTC, ghnoob commented on app.js
> +
no se si es de importancia esta linea

2022-08-10 14:08 UTC, ghnoob requested changes

2022-08-10 14:08 UTC, ghnoob commented on docs/swagger.js
> +    './docs/*.js'],
revisar que esten bien las rutas

2022-08-10 15:45 UTC, Samuel0023 approved these changes

2022-08-11 13:21 UTC, gabodmc requested changes
Solo una pequeña correccion, y guarda con subir archivos al pr que no son del scope. Esas cosas hay que hacerlas desde el source control del vsc

2022-08-11 13:21 UTC, gabodmc commented on docs/swagger.js
> +  apis: ['./routes/*.js',
Solo se van a documentar las rutas, por lo que apis: ['./routes/*.js'] estaria mas que bien

2022-08-11 16:50 UTC, ghnoob commented on docs/swagger.js
> +  apis: ['./routes/*.js',
en realidad es `../routes/*.js` porque cambio la ubicacion del archivo

2022-08-12 20:18 UTC, MRobertaMendoza commented on docs/swagger.js
> +  apis: ['./routes/*.js',
ok, ahí lo corrijo.

2022-08-12 20:24 UTC, MRobertaMendoza commented on docs/swagger.js
> +  apis: ['./routes/*.js',
ok, ahi lo corrijo...

2022-08-12 23:53 UTC, ghnoob requested changes

2022-08-12 23:53 UTC, ghnoob commented on docs/swagger.js
> +  apis: ['../routes/*.js',
fijate de pasarle una ruta absoluta porque si no lo haces no te lee los archivos.
te lo comento porque una vez me habia pasado eso, además probe usando esta configuracion con la doc que ya esta en main y no andaba
hablando en criollo seria
```js
// asi probe en mi maquina y ahi si leia los archivos
apis: [path.join(__dirname, '..', 'routes', '*.js')]
```

2022-08-13 00:21 UTC, MRobertaMendoza commented on docs/swagger.js
> +  apis: ['../routes/*.js',
OK, REVISO

2022-08-16 00:10 UTC, ghnoob approved these changes
Buenisimo

2022-08-16 00:30 UTC, gabodmc approved these changes

2022-08-16 02:44 UTC, ignacioborraz approved these changes

2022-08-16 07:59 UTC, merged